language: php

php:
  - 7.2

before_script:
  - cp .env.testing .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate

before_install:
  - mysql -e 'CREATE DATABASE wildcard_participa_tests;'

script:
  - phpunit

services:
  - mysql

notifications:
  email: false
